## 서버 포트 변경
server:
  port: 8088

## LOG 출력 레벨 설정
#logging:
#  level:
#    org.springframework: DEBUG

spring:
  messages: ## 다국어 설정
    basename: messages
  security: ## 스프링 시큐리티 인증 정보 설정
    user:
      name: username
      password: springpass

## Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
