## 서버 포트 변경
server:
  port: 8088

## LOG 출력 레벨 설정
#logging:
#  level:
#    org.springframework: DEBUG

## 다국어 설정
spring:
  messages:
    basename: messages

## Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"